// tests/oracle_test.cpp
//
// Tests for the Oracle backend (OCI) through the generic SQL gateway. Skipped
// unless a reachable Oracle instance is provided via three environment
// variables:
//   ORESHNEK_ORACLE_TEST_CONNECT  — Easy Connect string, e.g. "host:1521/XEPDB1"
//   ORESHNEK_ORACLE_TEST_USER     — schema/user to connect as
//   ORESHNEK_ORACLE_TEST_PASSWORD — its password
// When set, it runs the same assertions as db_test/pg_test against Oracle,
// starting from a clean slate. The framework is domain-agnostic, so the test
// owns its schema and SQL.
//
// Note: unlike SQLite/PostgreSQL, Oracle's SQL parser rejects a trailing `;`
// on plain (non-PL/SQL) statements, so none of the SQL below has one.

#include "oreshnek/platform/DatabaseManager.h"

#include <cstdlib>
#include <iostream>
#include <string>
#include <thread>
#include <vector>

using namespace Oreshnek::Platform;

namespace {
int g_failures = 0;
void check(bool cond, const std::string& msg) {
    if (!cond) {
        std::cerr << "[FAIL] " << msg << std::endl;
        ++g_failures;
    }
}

const char* env_or_null(const char* name) {
    const char* v = std::getenv(name);
    if (v == nullptr || v[0] == '\0') return nullptr;
    return v;
}
}  // namespace

int main() {
    const char* connect = env_or_null("ORESHNEK_ORACLE_TEST_CONNECT");
    const char* user = env_or_null("ORESHNEK_ORACLE_TEST_USER");
    const char* password = env_or_null("ORESHNEK_ORACLE_TEST_PASSWORD");
    if (connect == nullptr || user == nullptr || password == nullptr) {
        std::cout << "[SKIP] oracle_test: set ORESHNEK_ORACLE_TEST_CONNECT, "
                     "ORESHNEK_ORACLE_TEST_USER and ORESHNEK_ORACLE_TEST_PASSWORD to run "
                     "against Oracle"
                  << std::endl;
        return 0;
    }

    ServerConfig cfg;
    cfg.db.backend = "oracle";
    cfg.db.ora_connect_string = connect;
    cfg.db.ora_user = user;
    cfg.db.ora_password = password;
    cfg.db.ora_pool_size = 4;
    DatabaseManager db(cfg);

    // Drop the test table so the run is idempotent, tolerating "table does not
    // exist" (ORA-00942) on a first run. Oracle only supports
    // `DROP TABLE IF EXISTS` from 23c on, so this PL/SQL block is the portable
    // form across older servers too.
    check(db.exec("BEGIN "
                  "EXECUTE IMMEDIATE 'DROP TABLE widgets'; "
                  "EXCEPTION WHEN OTHERS THEN "
                  "IF SQLCODE != -942 THEN RAISE; END IF; "
                  "END;").ok,
          "drop existing table (idempotent)");

    // The application owns its schema; the framework just runs the SQL. Note
    // the Oracle dialect (IDENTITY column) — only the SQL changes, not the API.
    check(db.exec("CREATE TABLE widgets ("
                  "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                  "name VARCHAR2(200) UNIQUE NOT NULL, "
                  "note VARCHAR2(200), "  // nullable, for the NULL roundtrip below
                  "hits NUMBER DEFAULT 0 NOT NULL)")
              .ok,
          "create table");

    // --- Insert + parameterized read + unique constraint --------------------
    // Oracle has no implicit last-insert-id through this generic ?-params
    // interface (RETURNING ... INTO needs an OUT bind); read the IDENTITY back
    // with a plain SELECT instead.
    check(db.exec("INSERT INTO widgets (name) VALUES (?)", {"alice"}).ok, "insert succeeds");

    SqlResult idr = db.query("SELECT id FROM widgets WHERE name = ?", {"alice"});
    check(idr.ok && idr.row_count() == 1, "select finds the inserted row");
    const long long wid = idr.integer(0, 0);
    check(wid > 0, "generated id is positive");

    SqlResult got = db.query("SELECT id, name, hits FROM widgets WHERE name = ?", {"alice"});
    check(got.ok && got.row_count() == 1, "select finds the row");
    check(got.text(0, got.column("name")) == "alice", "name roundtrips");
    check(got.integer(0, got.column("hits")) == 0, "default hits == 0");

    check(!db.exec("INSERT INTO widgets (name) VALUES (?)", {"alice"}).ok,
          "duplicate name rejected (unique constraint)");
    check(db.query("SELECT id FROM widgets WHERE name = ?", {"nobody"}).empty(),
          "unknown row yields no tuples");

    // --- NULL roundtrip -----------------------------------------------------
    db.exec("INSERT INTO widgets (name, note) VALUES (?, ?)", {"nullable", std::nullopt});
    SqlResult nul = db.query("SELECT note FROM widgets WHERE name = ?", {"nullable"});
    check(nul.ok && nul.row_count() == 1 && nul.is_null(0, 0), "SQL NULL roundtrips");

    // --- Concurrent writers across the pool ---------------------------------
    constexpr int kThreads = 6;
    constexpr int kPerThread = 25;
    std::vector<std::thread> writers;
    for (int t = 0; t < kThreads; ++t) {
        writers.emplace_back([&db, t] {
            for (int i = 0; i < kPerThread; ++i) {
                db.exec("INSERT INTO widgets (name) VALUES (?)",
                        {"w-" + std::to_string(t) + "-" + std::to_string(i)});
            }
        });
    }
    for (auto& th : writers) th.join();

    SqlResult count = db.query("SELECT COUNT(*) FROM widgets");
    check(count.ok && count.integer(0, 0) == kThreads * kPerThread + 2,
          "all concurrently-inserted rows are present");

    // --- Concurrent increments on one row -----------------------------------
    constexpr int kIncThreads = 5;
    constexpr int kIncEach = 20;
    std::vector<std::thread> bumpers;
    for (int t = 0; t < kIncThreads; ++t) {
        bumpers.emplace_back([&db, wid] {
            for (int i = 0; i < kIncEach; ++i) {
                db.exec("UPDATE widgets SET hits = hits + 1 WHERE id = ?",
                        {std::to_string(wid)});
            }
        });
    }
    for (auto& th : bumpers) th.join();

    SqlResult hits = db.query("SELECT hits FROM widgets WHERE id = ?", {std::to_string(wid)});
    check(hits.ok && hits.integer(0, 0) == kIncThreads * kIncEach,
          "increments are exact under concurrency (no lost updates)");

    if (g_failures == 0) {
        std::cout << "[OK] all oracle tests passed" << std::endl;
        return 0;
    }
    std::cerr << "[FAILED] " << g_failures << " check(s) failed" << std::endl;
    return 1;
}
